# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: 'build/libs/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: votemanager
    repositoryName: hszemi/VoteManager
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.ArtifactStagingDirectory)/*.jar